{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import torch\n",
    "import torchvision\n",
    "import torch.nn as nn\n",
    "import numpy as np\n",
    "import torch.nn.functional as F\n",
    "from torchvision.datasets import ImageFolder\n",
    "from torch.utils.data import DataLoader\n",
    "from torch.utils.data import TensorDataset\n",
    "import torch.optim as optim\n",
    "import PIL\n",
    "from PIL import Image\n",
    "import torchvision.transforms as tt\n",
    "from torchvision.utils import make_grid\n",
    "import matplotlib.pyplot as plt\n",
    "%matplotlib inline\n",
    "import time\n",
    "from sklearn.model_selection import train_test_split\n",
    "from torch.autograd import Variable\n",
    "import pandas as pd\n",
    "import seaborn\n",
    "from facenet_pytorch import MTCNN\n",
    "import mediapipe as mp\n",
    "import cv2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "train_transforms = tt.Compose([tt.Grayscale(num_output_channels=1), # Картинки чернобелые\n",
    "                         \n",
    "                         # Настройки для расширения датасета\n",
    "                         tt.RandomHorizontalFlip(),           # Случайные повороты на 90 градусов\n",
    "                         tt.RandomRotation(30),               # Случайные повороты на 30 градусов\n",
    "                         #tt.Normalize((0.5), (0.5), inplace=True),\n",
    "                         tt.Resize(64),\n",
    "                         tt.RandomHorizontalFlip(),\n",
    "                         tt.ToTensor()])                      # Приведение к тензору\n",
    "\n",
    "test_transforms = tt.Compose([tt.Grayscale(num_output_channels=1), tt.Resize(64), tt.ToTensor()])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "data_dir = './gestures/'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3398, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\azhur\\AppData\\Local\\Temp\\ipykernel_836\\1307178586.py\", line 1, in <cell line: 1>\n",
      "    classes_train = os.listdir(data_dir + \"/train\")\n",
      "FileNotFoundError: [WinError 3] Системе не удается найти указанный путь: './gestures//train'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1993, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1118, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1012, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 865, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 799, in format_exception_as_a_whole\n",
      "    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 845, in get_records\n",
      "    style = stack_data.style_with_executing_node(style, \"bg:ansiyellow\")\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n",
      "    class NewStyle(style):\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pygments\\style.py\", line 91, in __new__\n",
      "    ndef[4] = colorformat(styledef[3:])\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pygments\\style.py\", line 58, in colorformat\n",
      "    assert False, \"wrong color format %r\" % text\n",
      "AssertionError: wrong color format 'ansiyellow'\n"
     ]
    }
   ],
   "source": [
    "classes_train = os.listdir(data_dir + \"/train\")\n",
    "classes_test = os.listdir(data_dir + \"/test\")\n",
    "print(f'Train Classes - {classes_train}')\n",
    "print(f'test Classes - {classes_test}')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "digit_to_classname = {0:'C', 1:'L', 2:'fist', 3:'ok', 4:'palm', 5:'peace'}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3398, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\azhur\\AppData\\Local\\Temp\\ipykernel_836\\2060642943.py\", line 1, in <cell line: 1>\n",
      "    train_dataset = ImageFolder(data_dir + '/train', train_transforms)\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\torchvision\\datasets\\folder.py\", line 309, in __init__\n",
      "    super().__init__(\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\torchvision\\datasets\\folder.py\", line 144, in __init__\n",
      "    classes, class_to_idx = self.find_classes(self.root)\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\torchvision\\datasets\\folder.py\", line 218, in find_classes\n",
      "    return find_classes(directory)\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\torchvision\\datasets\\folder.py\", line 40, in find_classes\n",
      "    classes = sorted(entry.name for entry in os.scandir(directory) if entry.is_dir())\n",
      "FileNotFoundError: [WinError 3] Системе не удается найти указанный путь: './gestures//train'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1993, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1118, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1012, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 865, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 799, in format_exception_as_a_whole\n",
      "    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 845, in get_records\n",
      "    style = stack_data.style_with_executing_node(style, \"bg:ansiyellow\")\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n",
      "    class NewStyle(style):\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pygments\\style.py\", line 91, in __new__\n",
      "    ndef[4] = colorformat(styledef[3:])\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pygments\\style.py\", line 58, in colorformat\n",
      "    assert False, \"wrong color format %r\" % text\n",
      "AssertionError: wrong color format 'ansiyellow'\n"
     ]
    }
   ],
   "source": [
    "train_dataset = ImageFolder(data_dir + '/train', train_transforms)\n",
    "test_dataset  = ImageFolder(data_dir + '/test', test_transforms)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "batch_size = 32"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3398, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\azhur\\AppData\\Local\\Temp\\ipykernel_836\\3865821944.py\", line 1, in <cell line: 1>\n",
      "    train_dataloader = DataLoader(train_dataset, batch_size, shuffle=True, num_workers=3, pin_memory=True)\n",
      "NameError: name 'train_dataset' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1993, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1118, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1012, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 865, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 799, in format_exception_as_a_whole\n",
      "    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 845, in get_records\n",
      "    style = stack_data.style_with_executing_node(style, \"bg:ansiyellow\")\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n",
      "    class NewStyle(style):\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pygments\\style.py\", line 91, in __new__\n",
      "    ndef[4] = colorformat(styledef[3:])\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pygments\\style.py\", line 58, in colorformat\n",
      "    assert False, \"wrong color format %r\" % text\n",
      "AssertionError: wrong color format 'ansiyellow'\n"
     ]
    }
   ],
   "source": [
    "train_dataloader = DataLoader(train_dataset, batch_size, shuffle=True, num_workers=3, pin_memory=True)\n",
    "test_dataloader = DataLoader(test_dataset, batch_size, num_workers=3, pin_memory=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [],
   "source": [
    "def show_batch(dl):\n",
    "    for images, labels in dl:\n",
    "        fig, ax = plt.subplots(figsize=(12, 12))\n",
    "        ax.set_xticks([]); ax.set_yticks([])\n",
    "        print(images[0].shape)\n",
    "        ax.imshow(make_grid(images[:64], nrow=8).permute(1, 2, 0))\n",
    "        break"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3398, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\azhur\\AppData\\Local\\Temp\\ipykernel_836\\2349060023.py\", line 1, in <cell line: 1>\n",
      "    show_batch(test_dataloader)\n",
      "NameError: name 'test_dataloader' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1993, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1118, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1012, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 865, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 799, in format_exception_as_a_whole\n",
      "    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 845, in get_records\n",
      "    style = stack_data.style_with_executing_node(style, \"bg:ansiyellow\")\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n",
      "    class NewStyle(style):\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pygments\\style.py\", line 91, in __new__\n",
      "    ndef[4] = colorformat(styledef[3:])\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pygments\\style.py\", line 58, in colorformat\n",
      "    assert False, \"wrong color format %r\" % text\n",
      "AssertionError: wrong color format 'ansiyellow'\n"
     ]
    }
   ],
   "source": [
    "show_batch(test_dataloader)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [],
   "source": [
    "def get_default_device():\n",
    "    if torch.cuda.is_available():\n",
    "        return torch.device('cuda')\n",
    "    else:\n",
    "        return torch.device('cpu')\n",
    "    \n",
    "def to_device(data, device):\n",
    "    if isinstance(data, (list,tuple)):\n",
    "        return [to_device(x, device) for x in data]\n",
    "    return data.to(device, non_blocking=True)\n",
    "\n",
    "class DeviceDataLoader():\n",
    "    def __init__(self, dl, device):\n",
    "        self.dl = dl\n",
    "        self.device = device\n",
    "        \n",
    "    def __iter__(self):\n",
    "        for b in self.dl: \n",
    "            yield to_device(b, self.device)\n",
    "\n",
    "    def __len__(self):\n",
    "        return len(self.dl)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "device(type='cpu')"
      ]
     },
     "execution_count": 14,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "device = get_default_device()\n",
    "device"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3398, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\azhur\\AppData\\Local\\Temp\\ipykernel_836\\3426753692.py\", line 1, in <cell line: 1>\n",
      "    train_dataloader = DeviceDataLoader(train_dataloader, device)\n",
      "NameError: name 'train_dataloader' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1993, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1118, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1012, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 865, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 799, in format_exception_as_a_whole\n",
      "    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 845, in get_records\n",
      "    style = stack_data.style_with_executing_node(style, \"bg:ansiyellow\")\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n",
      "    class NewStyle(style):\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pygments\\style.py\", line 91, in __new__\n",
      "    ndef[4] = colorformat(styledef[3:])\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pygments\\style.py\", line 58, in colorformat\n",
      "    assert False, \"wrong color format %r\" % text\n",
      "AssertionError: wrong color format 'ansiyellow'\n"
     ]
    }
   ],
   "source": [
    "train_dataloader = DeviceDataLoader(train_dataloader, device)\n",
    "test_dataloader = DeviceDataLoader(test_dataloader, device)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [],
   "source": [
    "class ResNet(nn.Module):\n",
    "    def __init__(self, in_chnls, num_cls):\n",
    "        super().__init__()\n",
    "        \n",
    "        self.conv1 = self.conv_block(in_chnls, 64, pool=True)           # 64x24x24 \n",
    "        self.conv2 = self.conv_block(64, 128, pool=True)                # 128x12x12\n",
    "        self.resnet1 = nn.Sequential(self.conv_block(128, 128), self.conv_block(128, 128))    # Resnet layer 1: includes 2 conv2d\n",
    "        \n",
    "        self.conv3 = self.conv_block(128, 256, pool=True)       # 256x6x6 \n",
    "        self.conv4 = self.conv_block(256, 512, pool=True)       # 512x3x3\n",
    "        self.resnet2 = nn.Sequential(self.conv_block(512, 512), self.conv_block(512, 512))    # Resnet layer 2: includes 2 conv2d\n",
    "        \n",
    "        self.classifier = nn.Sequential(nn.MaxPool2d(3),\n",
    "                                        nn.Flatten(),\n",
    "                                        nn.Linear(512, num_cls))    # num_cls\n",
    "        \n",
    "    @staticmethod\n",
    "    def conv_block(in_chnl, out_chnl, pool=False, padding=1):\n",
    "        layers = [\n",
    "            nn.Conv2d(in_chnl, out_chnl, kernel_size=3, padding=padding),\n",
    "            nn.BatchNorm2d(out_chnl),\n",
    "            nn.ReLU(inplace=True)]\n",
    "        if pool: layers.append(nn.MaxPool2d(2))\n",
    "        return nn.Sequential(*layers)\n",
    "        \n",
    "    def forward(self, xb):\n",
    "        out = self.conv1(xb)\n",
    "        out = self.conv2(out)\n",
    "        out = self.resnet1(out) + out\n",
    "        \n",
    "        out = self.conv3(out)\n",
    "        out = self.conv4(out)\n",
    "        out = self.resnet2(out) + out\n",
    "        \n",
    "        return self.classifier(out)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3398, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\azhur\\AppData\\Local\\Temp\\ipykernel_836\\3441460262.py\", line 1, in <cell line: 1>\n",
      "    model = to_device(ResNet(1, len(classes_train)), device)\n",
      "NameError: name 'classes_train' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1993, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1118, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1012, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 865, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 799, in format_exception_as_a_whole\n",
      "    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 845, in get_records\n",
      "    style = stack_data.style_with_executing_node(style, \"bg:ansiyellow\")\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n",
      "    class NewStyle(style):\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pygments\\style.py\", line 91, in __new__\n",
      "    ndef[4] = colorformat(styledef[3:])\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pygments\\style.py\", line 58, in colorformat\n",
      "    assert False, \"wrong color format %r\" % text\n",
      "AssertionError: wrong color format 'ansiyellow'\n"
     ]
    }
   ],
   "source": [
    "model = to_device(ResNet(1, len(classes_train)), device)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3398, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\azhur\\AppData\\Local\\Temp\\ipykernel_836\\2503943151.py\", line 9, in <cell line: 9>\n",
      "    optimizer = torch.optim.Adam(model.parameters(), max_lr)\n",
      "NameError: name 'model' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1993, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1118, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1012, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 865, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 799, in format_exception_as_a_whole\n",
      "    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 845, in get_records\n",
      "    style = stack_data.style_with_executing_node(style, \"bg:ansiyellow\")\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n",
      "    class NewStyle(style):\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pygments\\style.py\", line 91, in __new__\n",
      "    ndef[4] = colorformat(styledef[3:])\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pygments\\style.py\", line 58, in colorformat\n",
      "    assert False, \"wrong color format %r\" % text\n",
      "AssertionError: wrong color format 'ansiyellow'\n"
     ]
    }
   ],
   "source": [
    "if torch.cuda.is_available(): \n",
    "    torch.cuda.empty_cache()\n",
    "\n",
    "\n",
    "epochs = 20\n",
    "max_lr = 0.0001\n",
    "grad_clip = 0.1\n",
    "weight_decay = 1e-4\n",
    "optimizer = torch.optim.Adam(model.parameters(), max_lr)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3398, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\azhur\\AppData\\Local\\Temp\\ipykernel_836\\435303388.py\", line 1, in <cell line: 1>\n",
      "    total_steps = len(train_dataloader)\n",
      "NameError: name 'train_dataloader' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1993, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1118, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1012, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 865, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 799, in format_exception_as_a_whole\n",
      "    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 845, in get_records\n",
      "    style = stack_data.style_with_executing_node(style, \"bg:ansiyellow\")\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n",
      "    class NewStyle(style):\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pygments\\style.py\", line 91, in __new__\n",
      "    ndef[4] = colorformat(styledef[3:])\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pygments\\style.py\", line 58, in colorformat\n",
      "    assert False, \"wrong color format %r\" % text\n",
      "AssertionError: wrong color format 'ansiyellow'\n"
     ]
    }
   ],
   "source": [
    "total_steps = len(train_dataloader)\n",
    "print(f'{epochs} epochs, {total_steps} total_steps per epoch')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3398, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\azhur\\AppData\\Local\\Temp\\ipykernel_836\\3223885978.py\", line 1, in <cell line: 1>\n",
      "    scheduler = torch.optim.lr_scheduler.OneCycleLR(optimizer, max_lr, epochs=epochs,\n",
      "NameError: name 'optimizer' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1993, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1118, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1012, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 865, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 799, in format_exception_as_a_whole\n",
      "    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 845, in get_records\n",
      "    style = stack_data.style_with_executing_node(style, \"bg:ansiyellow\")\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n",
      "    class NewStyle(style):\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pygments\\style.py\", line 91, in __new__\n",
      "    ndef[4] = colorformat(styledef[3:])\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pygments\\style.py\", line 58, in colorformat\n",
      "    assert False, \"wrong color format %r\" % text\n",
      "AssertionError: wrong color format 'ansiyellow'\n"
     ]
    }
   ],
   "source": [
    "scheduler = torch.optim.lr_scheduler.OneCycleLR(optimizer, max_lr, epochs=epochs, \n",
    "                                                steps_per_epoch=len(train_dataloader))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3398, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\azhur\\AppData\\Local\\Temp\\ipykernel_836\\1622048781.py\", line 12, in <cell line: 7>\n",
      "    for batch_idx, (data, labels) in enumerate(train_dataloader):\n",
      "NameError: name 'train_dataloader' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1993, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1118, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1012, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 865, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 799, in format_exception_as_a_whole\n",
      "    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 845, in get_records\n",
      "    style = stack_data.style_with_executing_node(style, \"bg:ansiyellow\")\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n",
      "    class NewStyle(style):\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pygments\\style.py\", line 91, in __new__\n",
      "    ndef[4] = colorformat(styledef[3:])\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pygments\\style.py\", line 58, in colorformat\n",
      "    assert False, \"wrong color format %r\" % text\n",
      "AssertionError: wrong color format 'ansiyellow'\n"
     ]
    }
   ],
   "source": [
    "epoch_losses = []\n",
    "true_y = []\n",
    "pred_y = []\n",
    "\n",
    "sm=nn.Softmax(dim=0)\n",
    "\n",
    "for epoch in range(epochs):\n",
    "    \n",
    "    time1 = time.time()\n",
    "    running_loss = 0.0\n",
    "    epoch_loss = []\n",
    "    for batch_idx, (data, labels) in enumerate(train_dataloader):\n",
    "        data, labels = data.cuda(), labels.cuda()       \n",
    "        \n",
    "        optimizer.zero_grad()\n",
    "        \n",
    "        outputs = model(data)\n",
    "        \n",
    "#         print(outputs[0])\n",
    "        #print(labels[0])\n",
    "        _, preds = torch.max(outputs, 1)\n",
    "        #print(preds)\n",
    "        \n",
    "        true_y.append(labels.to('cpu'))\n",
    "        pred_y.append(outputs.to('cpu'))\n",
    "        \n",
    "        loss = F.cross_entropy(outputs, labels)\n",
    "        loss.backward()\n",
    "        optimizer.step()\n",
    "        scheduler.step()\n",
    "        \n",
    "        running_loss += loss.item()\n",
    "        epoch_loss.append(loss.item())\n",
    "        if (batch_idx+1) % 10000 == 9999:\n",
    "            print(f'Train Epoch: {epoch+1}, Loss: {running_loss/10000}')\n",
    "            time2 = time.time()\n",
    "            print(f'Spend time for 10000 images: {time2 - time1} sec')\n",
    "            time1 = time.time()\n",
    "            running_loss = 0.0\n",
    "    print(f'Epoch {epoch+1}, loss: ', np.mean(epoch_loss))\n",
    "    epoch_losses.append(epoch_loss)\n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Text(0.5, 1.0, 'losses vs. No. of epochs')"
      ]
     },
     "execution_count": 22,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAZAAAAEWCAYAAABIVsEJAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjYuMiwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8o6BhiAAAACXBIWXMAAAsTAAALEwEAmpwYAAAYQElEQVR4nO3de7hddX3n8fcnCUYQ5RoQiBBuXqBVrKdQa3mKcvdRwyBVvGa8DDMdfabWcWootiLaGcBR1JGO4qWDN0BxGFOdDgKKrTMKnFCqRqUJAQsR5I4gBQS+88f+pd2c7oSddbLPPse8X8+znrPWb/3WWt/fPsn+7LXWPnunqpAkaVPNG3cBkqS5yQCRJHVigEiSOjFAJEmdGCCSpE4MEElSJwaIZkySG5IcMe46tiRJXpBkdZL7khw3C+pZkqSSLBh3LZo+A0QasSSXJ3kgydP62o5IcsMMHP404KNVtW1V/a8ZOJ62IAaINDN+AfzJGI67F7BqDMfVFsAA0VgkWZjkQ0l+2qYPJVnY1u2c5KtJ7k5yZ5K/STKvrXtnknVJ7k1ybZLDW/u8JMuTXJfkjiRfTLJjW/fEJJ9r7XcnuSrJrgNqemeSC6e0fTjJR9r8v06yth37+iSv2YQhfwR4VZJ9N/B4PKudqdydZFWSlw274yT/Jsma9litSLJ7a78O2Af4y3YJa+GAbXdP8uUkt7Ux/Ye+dacmuTDJBW3MVyd5zjA1J9k6yQeS/CTJPUm+nWTrvkO/Jsk/JLk9ySl92x2cZDLJz5P8LMkHh30cNAZV5eQ0IxNwA3BEmz8N+C6wC7AI+H/Ae9u6/wJ8DNiqTYcCAZ4B3Ajs3votAfZt83/Q9rcYWAh8HDivrfu3wF8C2wDzgecBTxlQ317A/cCT2/J84Gbgt4AnAT8HntHW7QYcOOS4LwfeDHwQ+FxrOwK4oc1vBawB/hh4AvAi4N71x3qcfb8IuB34jTbu/wb89aDHfMC284CVwJ+24+4DrAWObutPBX4JnNBqfAdwfd/vZYM1A2e3ce/RHsffbvUtAQr4BLA18BzgQeBZbbvvAK9r89sCvzXuf7dOG/n3N+4CnLacaUqAXAe8uG/d0X1PqKcBXwH2m7L9fsCt7cl3qynrfgQc3re8W3vyWwC8kV5APXuIGr8NvL7NHwlc1+afBNwNvBzYehPHvT5AFgH3AAdOCZBDgVuAeX3bnAecOsS+PwWc2be8bRv3kqmP+YBtDwH+YUrbycBftPlTge/2rZtHL1AP3VjNrd8/As8ZcMz1AbK4r+1K4MQ2/9fAe4Cdx/3v1enxJy9haVx2B37St/yT1gbwfnqvbr/eLhktB6iqNcDb6D1J3Zrk/PWXa+idPVzULqfcTS9QHgF2BT4LXAyc3y6XnZlkqw3U9QXgVW3+1W2ZqvoF8Erg3wE3J/lakmduyoCr6jbgo/QCcupjcWNVPTrl8dhjiN0+5nGsqvuAO4bcdi9g9/WPWXvc/pjeY7bejX37fhS4qR1zYzXvDDyR3ouEDbmlb/5+esEH8Cbg6cCP26XGlwwxDo2JAaJx+Sm9J7D19mxtVNW9VfUfq2of4GXA29ff66iqL1TV77RtCzijbX8jcGxVbd83PbGq1lXVL6vqPVV1AL1LKS8BXr+Bur4EHJZkMfCvaAHSjn1xVR1J7+zmx/Quw2yq9wMvpHcZrf+xeNr6+zx9j8e6Ifb3mMcxyZOAnYbc9kbg+imP2ZOr6sV9ffrfOTaP3iXCnz5OzbcDDwAD7/dsTFWtrqpX0bu0eQZwYRuTZiEDRONyHvCuJIuS7EzvOvznAJK8JMl+SULvks8jwKNJnpHkRe1m8AP0LpOsfwX8MeDPkuzV9rEoydI2/8Ikv55kPr37GL/s2+4x2lnC5cBf0Hty/VHbx65JlrYnsweB+za0j42pqruBDwB/1Nd8Bb1X4X+UZKskhwEvBc4fYpfnAW9IclB7XP4zcEVV3TDEtlcC97Y3D2ydZH6SX0vym319npfk+PT+buNt9Mb+3Y3V3M5KPg18sN2kn5/k+YNu4k+V5LVJFrV93N2aN/lx1swwQDQu7wMmge8B3weubm0A+wOX0nuS/g7w51X1TXo3YU+n9wr3FnqvUk9u23wYWEHvste99J7kDmnrngpcSC88fgR8i95lrQ35Ar17FF/oa5sHvJ3eK+87gd8Ffh8gyaFJ7tuEsX+YXigCUFUP0XvyPbaN7c/p3Yf5cdv/XyX540E7qqpL6b09+Mv07k/sC5w4TBFV9Qi9s7GD6N0cvx34JLBdX7ev0Lt0dxfwOuD4dka30Zrp3XD/PnAVvcfrDIZ7vjkGWNUezw/Tuzfyj8OMRzMvVX6hlKR/Kcmp9N7I8Npx16LZyTMQSVInBogkqRMvYUmSOvEMRJLUyRb1kco777xzLVmyZNxlSNKcsnLlyturatHU9i0qQJYsWcLk5OS4y5CkOSXJTwa1ewlLktSJASJJ6sQAkSR1YoBIkjoxQCRJnRggkqRODBBJUicGiCSpEwNEktSJASJJ6sQAkSR1YoBIkjoxQCRJnRggkqRODBBJUicGiCSpEwNEktSJASJJ6sQAkSR1YoBIkjoxQCRJnRggkqRODBBJUicGiCSpEwNEktTJWAMkyTFJrk2yJsnyAesXJrmgrb8iyZIp6/dMcl+Sd8xY0ZIkYIwBkmQ+cDZwLHAA8KokB0zp9ibgrqraDzgLOGPK+g8CfzXqWiVJ/9I4z0AOBtZU1dqqegg4H1g6pc9S4Nw2fyFweJIAJDkOuB5YNTPlSpL6jTNA9gBu7Fu+qbUN7FNVDwP3ADsl2RZ4J/CexztIkpOSTCaZvO222zZL4ZKkuXsT/VTgrKq67/E6VtU5VTVRVROLFi0afWWStIVYMMZjrwOe1re8uLUN6nNTkgXAdsAdwCHACUnOBLYHHk3yQFV9dORVS5KA8QbIVcD+SfamFxQnAq+e0mcFsAz4DnAC8I2qKuDQ9R2SnArcZ3hI0swaW4BU1cNJ3gpcDMwHPl1Vq5KcBkxW1QrgU8Bnk6wB7qQXMpKkWSC9F/RbhomJiZqcnBx3GZI0pyRZWVUTU9vn6k10SdKYGSCSpE4MEElSJwaIJKkTA0SS1IkBIknqxACRJHVigEiSOjFAJEmdGCCSpE4MEElSJwaIJKkTA0SS1IkBIknqxACRJHVigEiSOjFAJEmdGCCSpE4MEElSJwaIJKkTA0SS1IkBIknqxACRJHVigEiSOjFAJEmdGCCSpE4MEElSJwaIJKkTA0SS1IkBIknqZKwBkuSYJNcmWZNk+YD1C5Nc0NZfkWRJaz8yycok328/XzTjxUvSFm5sAZJkPnA2cCxwAPCqJAdM6fYm4K6q2g84Czijtd8OvLSqfh1YBnx2ZqqWJK03zjOQg4E1VbW2qh4CzgeWTumzFDi3zV8IHJ4kVfW3VfXT1r4K2DrJwhmpWpIEjDdA9gBu7Fu+qbUN7FNVDwP3ADtN6fNy4OqqenBEdUqSBlgw7gKmI8mB9C5rHbWRPicBJwHsueeeM1SZJP3qG+cZyDrgaX3Li1vbwD5JFgDbAXe05cXARcDrq+q6DR2kqs6pqomqmli0aNFmLF+StmzjDJCrgP2T7J3kCcCJwIopfVbQu0kOcALwjaqqJNsDXwOWV9X/namCJUn/bGwB0u5pvBW4GPgR8MWqWpXktCQva90+BeyUZA3wdmD9W33fCuwH/GmSa9q0ywwPQZK2aKmqcdcwYyYmJmpycnLcZUjSnJJkZVVNTG33L9ElSZ0YIJKkTgwQSVInBogkqRMDRJLUiQEiSerEAJEkdWKASJI6MUAkSZ0YIJKkTgwQSVInBogkqRMDRJLUiQEiSerEAJEkdWKASJI6MUAkSZ0YIJKkTgwQSVInBogkqRMDRJLUySYHSJIdkjx7FMVIkuaOoQIkyeVJnpJkR+Bq4BNJPjja0iRJs9mwZyDbVdXPgeOBz1TVIcARoytLkjTbDRsgC5LsBrwC+OoI65EkzRHDBshpwMXAdVV1VZJ9gNWjK0uSNNstGKZTVX0J+FLf8lrg5aMqSpI0+w17E/3pSS5L8oO2/Owk7xptaZKk2WzYS1ifAE4GfglQVd8DThxVUZKk2W/YANmmqq6c0vbw5i5GkjR3DBsgtyfZFyiAJCcAN4+sKknSrDdsgLwF+DjwzCTrgLcBvz/dgyc5Jsm1SdYkWT5g/cIkF7T1VyRZ0rfu5NZ+bZKjp1uLJGnTDPsurLXAEUmeBMyrqnune+Ak84GzgSOBm4Crkqyoqh/2dXsTcFdV7ZfkROAM4JVJDqB3D+ZAYHfg0iRPr6pHpluXJGk4w74L6w+SPAW4HzgrydVJjprmsQ8G1lTV2qp6CDgfWDqlz1Lg3DZ/IXB4krT286vqwaq6HljT9idJmiHDXsJ6Y/sok6OAnYDXAadP89h7ADf2Ld/U2gb2qaqHgXva8YfZFoAkJyWZTDJ52223TbNkSdJ6wwZI2s8X0/ssrFV9bbNaVZ1TVRNVNbFo0aJxlyNJvzKGDZCVSb5OL0AuTvJk4NFpHnsd8LS+5cWtbWCfJAuA7YA7htxWkjRCwwbIm4DlwG9W1f3AVsAbpnnsq4D9k+yd5An0boqvmNJnBbCszZ8AfKOqqrWf2N6ltTewPzD171QkSSM01LuwgOcD11TVL5K8FvgN4MPTOXBVPZzkrfQ+pHE+8OmqWpXkNGCyqlYAnwI+m2QNcCftr99bvy8CP6T3B41v8R1YkjSz0ntB/zidku8BzwGeDfwP4JPAK6rqd0da3WY2MTFRk5OT4y5DkuaUJCuramJq+7CXsB5ul46WAh+tqrOBJ2/OAiVJc8uwl7DuTXIyvbfvHppkHr37IJKkLdSwZyCvBB6k9/cgt9B719P7R1aVJGnWGypAWmh8HtguyUuAB6rqMyOtTJI0qw37USavoPc22d+j973oV7RP5JUkbaGGvQdyCr2/AbkVIMki4FJ6n08lSdoCDXsPZN768Gju2IRtJUm/goY9A/k/SS4GzmvLrwT+92hKkiTNBcN+H8h/SvJy4AWt6Zyqumh0ZUmSZrthz0Coqi8DXx5hLZKkOWSjAZLkXtr3oE9dBVRVPWUkVUmSZr2NBkhV+XElkqSBfCeVJKkTA0SS1IkBIknqxACRJHVigEiSOjFAJEmdGCCSpE4MEElSJwaIJKkTA0SS1IkBIknqxACRJHVigEiSOjFAJEmdGCCSpE4MEElSJwaIJKkTA0SS1MlYAiTJjkkuSbK6/dxhA/2WtT6rkyxrbdsk+VqSHydZleT0ma1ekgTjOwNZDlxWVfsDl7Xlx0iyI/Bu4BDgYODdfUHzX6vqmcBzgRckOXZmypYkrTeuAFkKnNvmzwWOG9DnaOCSqrqzqu4CLgGOqar7q+qbAFX1EHA1sHj0JUuS+o0rQHatqpvb/C3ArgP67AHc2Ld8U2v7J0m2B15K7yxGkjSDFoxqx0kuBZ46YNUp/QtVVUmqw/4XAOcBH6mqtRvpdxJwEsCee+65qYeRJG3AyAKkqo7Y0LokP0uyW1XdnGQ34NYB3dYBh/UtLwYu71s+B1hdVR96nDrOaX2ZmJjY5KCSJA02rktYK4BlbX4Z8JUBfS4GjkqyQ7t5flRrI8n7gO2At42+VEnSIOMKkNOBI5OsBo5oyySZSPJJgKq6E3gvcFWbTquqO5MspncZ7ADg6iTXJHnzOAYhSVuyVG05V3UmJiZqcnJy3GVI0pySZGVVTUxt9y/RJUmdGCCSpE4MEElSJwaIJKkTA0SS1IkBIknqxACRJHVigEiSOjFAJEmdGCCSpE4MEElSJwaIJKkTA0SS1IkBIknqxACRJHVigEiSOjFAJEmdGCCSpE4MEElSJwaIJKkTA0SS1IkBIknqxACRJHVigEiSOjFAJEmdGCCSpE4MEElSJwaIJKkTA0SS1IkBIknqxACRJHUylgBJsmOSS5Ksbj932EC/Za3P6iTLBqxfkeQHo69YkjTVuM5AlgOXVdX+wGVt+TGS7Ai8GzgEOBh4d3/QJDkeuG9mypUkTTWuAFkKnNvmzwWOG9DnaOCSqrqzqu4CLgGOAUiyLfB24H2jL1WSNMi4AmTXqrq5zd8C7Dqgzx7AjX3LN7U2gPcCHwDuf7wDJTkpyWSSydtuu20aJUuS+i0Y1Y6TXAo8dcCqU/oXqqqS1Cbs9yBg36r6wyRLHq9/VZ0DnAMwMTEx9HEkSRs3sgCpqiM2tC7Jz5LsVlU3J9kNuHVAt3XAYX3Li4HLgecDE0luoFf/Lkkur6rDkCTNmHFdwloBrH9X1TLgKwP6XAwclWSHdvP8KODiqvrvVbV7VS0Bfgf4e8NDkmbeuALkdODIJKuBI9oySSaSfBKgqu6kd6/jqjad1tokSbNAqrac2wITExM1OTk57jIkaU5JsrKqJqa2+5fokqRODBBJUicGiCSpEwNEktSJASJJ6sQAkSR1YoBIkjoxQCRJnRggkqRODBBJUicGiCSpEwNEktSJASJJ6sQAkSR1YoBIkjoxQCRJnRggkqRODBBJUicGiCSpEwNEktSJASJJ6sQAkSR1YoBIkjoxQCRJnaSqxl3DjElyG/CTcdexiXYGbh93ETPMMW8ZHPPcsVdVLZrauEUFyFyUZLKqJsZdx0xyzFsGxzz3eQlLktSJASJJ6sQAmf3OGXcBY+CYtwyOeY7zHogkqRPPQCRJnRggkqRODJBZIMmOSS5Jsrr93GED/Za1PquTLBuwfkWSH4y+4umbzpiTbJPka0l+nGRVktNntvpNk+SYJNcmWZNk+YD1C5Nc0NZfkWRJ37qTW/u1SY6e0cKnoeuYkxyZZGWS77efL5rx4juYzu+4rd8zyX1J3jFjRW8OVeU05gk4E1je5pcDZwzosyOwtv3coc3v0Lf+eOALwA/GPZ5RjxnYBnhh6/ME4G+AY8c9pg2Mcz5wHbBPq/XvgAOm9Pn3wMfa/InABW3+gNZ/IbB328/8cY9pxGN+LrB7m/81YN24xzPK8fatvxD4EvCOcY9nUybPQGaHpcC5bf5c4LgBfY4GLqmqO6vqLuAS4BiAJNsCbwfeN/pSN5vOY66q+6vqmwBV9RBwNbB49CV3cjCwpqrWtlrPpzf2fv2PxYXA4UnS2s+vqger6npgTdvfbNd5zFX1t1X109a+Ctg6ycIZqbq76fyOSXIccD298c4pBsjssGtV3dzmbwF2HdBnD+DGvuWbWhvAe4EPAPePrMLNb7pjBiDJ9sBLgctGUOPm8Lhj6O9TVQ8D9wA7DbntbDSdMfd7OXB1VT04ojo3l87jbS/+3gm8Zwbq3OwWjLuALUWSS4GnDlh1Sv9CVVWSod9bneQgYN+q+sOp11XHbVRj7tv/AuA84CNVtbZblZqNkhwInAEcNe5aRuxU4Kyquq+dkMwpBsgMqaojNrQuyc+S7FZVNyfZDbh1QLd1wGF9y4uBy4HnAxNJbqD3+9wlyeVVdRhjNsIxr3cOsLqqPjT9akdmHfC0vuXFrW1Qn5taKG4H3DHktrPRdMZMksXARcDrq+q60Zc7bdMZ7yHACUnOBLYHHk3yQFV9dORVbw7jvgnjVADv57E3lM8c0GdHetdJd2jT9cCOU/osYe7cRJ/WmOnd7/kyMG/cY3mccS6gd/N/b/75BuuBU/q8hcfeYP1imz+Qx95EX8vcuIk+nTFv3/ofP+5xzMR4p/Q5lTl2E33sBTgV9K79XgasBi7te5KcAD7Z1++N9G6krgHeMGA/cylAOo+Z3iu8An4EXNOmN497TBsZ64uBv6f3Tp1TWttpwMva/BPpvQNnDXAlsE/ftqe07a5llr7TbHOOGXgX8Iu+3+s1wC7jHs8of8d9+5hzAeJHmUiSOvFdWJKkTgwQSVInBogkqRMDRJLUiQEiSerEAJHmgCSHJfnquOuQ+hkgkqRODBBpM0ry2iRXJrkmyceTzG/f83BW++6Sy5Isan0PSvLdJN9LctH670RJsl+SS5P8XZKrk+zbdr9tkgvb96B8fv2nuUrjYoBIm0mSZwGvBF5QVQcBjwCvAZ4ETFbVgcC3gHe3TT4DvLOqng18v6/988DZVfUc4LeB9Z9a/FzgbfS+J2Qf4AUjHpK0UX6YorT5HA48D7iqnRxsTe9DIh8FLmh9Pgf8zyTbAdtX1bda+7nAl5I8Gdijqi4CqKoHANr+rqyqm9ryNfQ+uubbIx+VtAEGiLT5BDi3qk5+TGPyJ1P6df38oP7vxXgE//9qzLyEJW0+l9H7aO5d4J++930vev/PTmh9Xg18u6ruAe5Kcmhrfx3wraq6l95Hfh/X9rEwyTYzOQhpWL6CkTaTqvphkncBX08yD/glvY/x/gVwcFt3K737JADLgI+1gFgLvKG1vw74eJLT2j5+bwaHIQ3NT+OVRizJfVW17bjrkDY3L2FJkjrxDESS1IlnIJKkTgwQSVInBogkqRMDRJLUiQEiSerk/wPX06pVJJH48AAAAABJRU5ErkJggg==",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "losses = [np.mean(loss) for loss in epoch_losses]\n",
    "plt.plot(losses, '-x')\n",
    "plt.xlabel('epoch')\n",
    "plt.ylabel('losses')\n",
    "plt.title('losses vs. No. of epochs')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3398, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\azhur\\AppData\\Local\\Temp\\ipykernel_836\\1557795369.py\", line 1, in <cell line: 1>\n",
      "    torch.save(model.state_dict(), './models/gesture_detection_model_state_20_epochs.pth')\n",
      "NameError: name 'model' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1993, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1118, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1012, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 865, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 799, in format_exception_as_a_whole\n",
      "    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 845, in get_records\n",
      "    style = stack_data.style_with_executing_node(style, \"bg:ansiyellow\")\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n",
      "    class NewStyle(style):\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pygments\\style.py\", line 91, in __new__\n",
      "    ndef[4] = colorformat(styledef[3:])\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pygments\\style.py\", line 58, in colorformat\n",
      "    assert False, \"wrong color format %r\" % text\n",
      "AssertionError: wrong color format 'ansiyellow'\n"
     ]
    }
   ],
   "source": [
    "torch.save(model.state_dict(), './models/gesture_detection_model_state_20_epochs.pth')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3398, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\azhur\\AppData\\Local\\Temp\\ipykernel_836\\3269299696.py\", line 1, in <cell line: 1>\n",
      "    net=ResNet(1, len(classes_train)).to(device)\n",
      "NameError: name 'classes_train' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1993, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1118, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1012, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 865, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 799, in format_exception_as_a_whole\n",
      "    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 845, in get_records\n",
      "    style = stack_data.style_with_executing_node(style, \"bg:ansiyellow\")\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n",
      "    class NewStyle(style):\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pygments\\style.py\", line 91, in __new__\n",
      "    ndef[4] = colorformat(styledef[3:])\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pygments\\style.py\", line 58, in colorformat\n",
      "    assert False, \"wrong color format %r\" % text\n",
      "AssertionError: wrong color format 'ansiyellow'\n"
     ]
    }
   ],
   "source": [
    "net=ResNet(1, len(classes_train)).to(device)\n",
    "net.load_state_dict(torch.load('./models/gesture_detection_model_state_20_epochs.pth'))\n",
    "net.eval()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3398, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\azhur\\AppData\\Local\\Temp\\ipykernel_836\\26494400.py\", line 2, in <cell line: 1>\n",
      "    for i, data in enumerate(test_dataloader):\n",
      "NameError: name 'test_dataloader' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1993, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1118, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1012, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 865, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 799, in format_exception_as_a_whole\n",
      "    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 845, in get_records\n",
      "    style = stack_data.style_with_executing_node(style, \"bg:ansiyellow\")\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n",
      "    class NewStyle(style):\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pygments\\style.py\", line 91, in __new__\n",
      "    ndef[4] = colorformat(styledef[3:])\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pygments\\style.py\", line 58, in colorformat\n",
      "    assert False, \"wrong color format %r\" % text\n",
      "AssertionError: wrong color format 'ansiyellow'\n"
     ]
    }
   ],
   "source": [
    "with torch.no_grad():\n",
    "    for i, data in enumerate(test_dataloader):\n",
    "        images, labels = data\n",
    "        images, labels = images, labels\n",
    "        outputs = net(images)\n",
    "        print(images.shape)\n",
    "        print(outputs[0].shape)\n",
    "        plt.title(f'gaused - {digit_to_classname[outputs[0].argmax().item()]}, groud truth - {digit_to_classname[labels[0].data.item()]}')\n",
    "        plt.imshow(images[0].cpu().squeeze(), cmap='gray')\n",
    "        plt.show()\n",
    "        if i>10:\n",
    "            break"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3398, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\azhur\\AppData\\Local\\Temp\\ipykernel_836\\2417838103.py\", line 4, in <cell line: 3>\n",
      "    for i, (inputs, classes) in enumerate(test_dataloader):\n",
      "NameError: name 'test_dataloader' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1993, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1118, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1012, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 865, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 799, in format_exception_as_a_whole\n",
      "    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 845, in get_records\n",
      "    style = stack_data.style_with_executing_node(style, \"bg:ansiyellow\")\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n",
      "    class NewStyle(style):\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pygments\\style.py\", line 91, in __new__\n",
      "    ndef[4] = colorformat(styledef[3:])\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pygments\\style.py\", line 58, in colorformat\n",
      "    assert False, \"wrong color format %r\" % text\n",
      "AssertionError: wrong color format 'ansiyellow'\n"
     ]
    }
   ],
   "source": [
    "confusion_matrix = torch.zeros(6, 6)\n",
    "\n",
    "with torch.no_grad():\n",
    "    for i, (inputs, classes) in enumerate(test_dataloader):\n",
    "        inputs = inputs.to(device)\n",
    "        classes = classes.to(device)\n",
    "        outputs = net(inputs)\n",
    "        _, preds = torch.max(outputs, 1)\n",
    "        for t, p in zip(classes.view(-1), preds.view(-1)):\n",
    "                confusion_matrix[t.long(), p.long()] += 1\n",
    "\n",
    "plt.figure(figsize=(15,10))\n",
    "\n",
    "class_names = list(digit_to_classname.values())\n",
    "df_cm = pd.DataFrame(confusion_matrix, index=class_names, columns=class_names).astype(int)\n",
    "heatmap = seaborn.heatmap(df_cm, annot=True, fmt=\"d\")\n",
    "\n",
    "heatmap.yaxis.set_ticklabels(heatmap.yaxis.get_ticklabels(), rotation=0, ha='right',fontsize=15)\n",
    "heatmap.xaxis.set_ticklabels(heatmap.xaxis.get_ticklabels(), rotation=45, ha='right',fontsize=15)\n",
    "plt.ylabel('True label')\n",
    "plt.xlabel('Predicted label')\n",
    ";"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "from facenet_pytorch import MTCNN\n",
    "from PIL import Image\n",
    "import mediapipe as mp\n",
    "import cv2\n",
    "# mp_drawing = mp.solutions.drawing_utils\n",
    "# mp_hands = mp.solutions.hands\n",
    " \n",
    "\n",
    "# Класс детектирования и обработки лица с веб-камеры \n",
    "class FaceDetector(object):\n",
    "\n",
    "    def __init__(self, mtcnn, mp, resnet,channels=1):\n",
    "        # Создаем объект для считывания потока с веб-камеры(обычно вебкамера идет под номером 0. иногда 1)\n",
    "        self.cap = cv2.VideoCapture(0) \n",
    "        self.mtcnn = mtcnn\n",
    "        self.device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')\n",
    "        self.emodel = resnet\n",
    "        self.channels = channels\n",
    "        self.mp = mp\n",
    "\n",
    "    # Функция рисования найденных параметров на кадре\n",
    "    def _draw(self, frame, boxes, probs, landmarks):\n",
    "        try:\n",
    "            for box, prob, ld in zip(boxes, probs, landmarks):\n",
    "                # Рисуем обрамляющий прямоугольник лица на кадре\n",
    "                cv2.rectangle(frame,\n",
    "                              (int(box[0]), int(box[1])),\n",
    "                              (int(box[2]), int(box[3])),\n",
    "                              (0, 0, 255),\n",
    "                              thickness=2)\n",
    "                \n",
    "\n",
    "                # пишем на кадре какая эмоция распознана\n",
    "#                 cv2.putText(frame, \n",
    "#                     emotion, (int(box[2]), int(box[3])), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 255), 2, cv2.LINE_AA)\n",
    "\n",
    "                # Рисуем особенные точки\n",
    "#                 cv2.circle(frame, (int(ld[0][0]),int(ld[0][1])), 5, (0, 0, 255), -1)\n",
    "#                 cv2.circle(frame, (int(ld[1][0]),int(ld[1][1])), 5, (0, 0, 255), -1)\n",
    "#                 cv2.circle(frame, (int(ld[2][0]),int(ld[2][1])), 5, (0, 0, 255), -1)\n",
    "#                 cv2.circle(frame, (int(ld[3][0]),int(ld[3][1])), 5, (0, 0, 255), -1)\n",
    "#                 cv2.circle(frame, (int(ld[4][0]),int(ld[4][1])), 5, (0, 0, 255), -1)\n",
    "        except Exception as e:\n",
    "            print('Something wrong im draw function!')\n",
    "            print(f'error : {e}')\n",
    "\n",
    "        return frame\n",
    "    \n",
    "    # Функция для вырезания лиц с кадра\n",
    "    @staticmethod\n",
    "    def crop_faces(frame, boxes):\n",
    "        faces = []\n",
    "        for i, box in enumerate(boxes):\n",
    "            faces.append(frame[int(box[1]-40):int(box[3]+40), \n",
    "                int(box[0]-40):int(box[2]+40)])\n",
    "#             print(box)\n",
    "        return faces\n",
    "    \n",
    "    @staticmethod\n",
    "    def crop_hands(frame, hand_boxes):\n",
    "        hands = []\n",
    "        for i, hand_box in enumerate(hand_boxes):\n",
    "            hands.append(frame[int(hand_box[1]-60):int(hand_box[3]+60), \n",
    "                int(hand_box[0]-60):int(hand_box[2]+60)])\n",
    "        return hands\n",
    "    \n",
    "    @staticmethod\n",
    "    def digit_to_classname(digit):\n",
    "        if digit == 0:\n",
    "            return 'C'\n",
    "        elif digit == 1:\n",
    "            return 'L'\n",
    "        elif digit == 2:\n",
    "            return 'fist'\n",
    "        elif digit == 3:\n",
    "            return 'ok'\n",
    "        elif digit == 4:\n",
    "            return 'palm'\n",
    "        elif digit == 5:\n",
    "            return 'peace'\n",
    "        \n",
    "    @staticmethod\n",
    "    def remove_background(frame):\n",
    "        bgModel = cv2.createBackgroundSubtractorMOG2(0, 50)\n",
    "        fgmask = bgModel.apply(frame, learningRate=0)\n",
    "        kernel = np.ones((3, 3), np.uint8)\n",
    "        fgmask = cv2.erode(fgmask, kernel, iterations=1)\n",
    "        res = cv2.bitwise_and(frame, frame, mask=fgmask)\n",
    "        return res  \n",
    "    \n",
    "    # Функция в которой будет происходить процесс считывания и обработки каждого кадра\n",
    "    def run(self):\n",
    "\n",
    "        blurValue = 5  # GaussianBlur parameter\n",
    "\n",
    "        \n",
    "        mp_drawing = self.mp.solutions.drawing_utils\n",
    "        mp_hands = self.mp.solutions.hands\n",
    "        with mp_hands.Hands(\n",
    "    min_detection_confidence=0.5,\n",
    "    min_tracking_confidence=0.5) as hands:\n",
    "        # Заходим в бесконечный цикл\n",
    "            while True:\n",
    "                # Считываем каждый новый кадр - frame\n",
    "                # ret - логическая переменая. Смысл - считали ли мы кадр с потока или нет\n",
    "                ret, frame = self.cap.read()\n",
    "                h, w, c = frame.shape\n",
    "                try:\n",
    "                    # детектируем расположение лица на кадре, вероятности на сколько это лицо\n",
    "                    # и особенные точки лица\n",
    "                    boxes, probs, landmarks = self.mtcnn.detect(frame, landmarks=True)\n",
    "\n",
    "\n",
    "\n",
    "    #                 # Вырезаем лицо из кадра\n",
    "                    face = self.crop_faces(frame, boxes)[0]\n",
    "\n",
    "                    # Рисуем на кадре\n",
    "                    self._draw(frame, boxes, probs, landmarks)\n",
    "\n",
    "#                     img = self.remove_background(frame)\n",
    "                    frame = cv2.cvtColor(cv2.flip(frame, 1), cv2.COLOR_BGR2RGB)\n",
    "                    # To improve performance, optionally mark the image as not writeable to\n",
    "                    # pass by reference.\n",
    "                    frame.flags.writeable = False\n",
    "                    results = hands.process(frame)\n",
    "\n",
    "                    # Draw the hand annotations on the image.\n",
    "                    frame.flags.writeable = True\n",
    "                    frame = cv2.cvtColor(frame, cv2.COLOR_RGB2BGR)\n",
    "                    hand_landmarks = results.multi_hand_landmarks\n",
    "                    if hand_landmarks:\n",
    "                        hand_boxes = []\n",
    "                        for handLMs in hand_landmarks:\n",
    "#                             hand_box = []\n",
    "                            x_max = 0\n",
    "                            y_max = 0\n",
    "                            x_min = w\n",
    "                            y_min = h\n",
    "                            \n",
    "                            for lm in handLMs.landmark:\n",
    "#                                 \n",
    "                                x, y = int(lm.x * w), int(lm.y * h)\n",
    "                                if x > x_max:\n",
    "                                    x_max = x\n",
    "                                if x < x_min:\n",
    "                                    x_min = x\n",
    "                                if y > y_max:\n",
    "                                    y_max = y\n",
    "                                if y < y_min:\n",
    "                                    y_min = y\n",
    "#                             hand_box.append(x_min, y_min, x_max, y_max)\n",
    "#                             hand_boxes.append(hand_box)\n",
    "#                         print(handLMs)\n",
    "#                         hand_cv = cv2.rectangle(frame, (x_min, y_min), (x_max, y_max), (0, 255, 0), 2)\n",
    "                        hand_box = [x_min, y_min, x_max, y_max]\n",
    "                        hand_boxes.append(hand_box)\n",
    "\n",
    "#                         mp_drawing.draw_landmarks(frame, handLMs, mp_hands.HAND_CONNECTIONS)\n",
    "                        # Вырезаем руку с кадра\n",
    "                        hand = self.crop_hands(frame, hand_boxes)[0]\n",
    "                        \n",
    "                        # Меняем размер изображения лица для входа в нейронную сеть\n",
    "                        hand_img = cv2.resize(hand,(71,64))\n",
    "                        \n",
    "                        hand = cv2.cvtColor(hand_img, cv2.COLOR_BGR2RGB)\n",
    "                        # Превращаем в 1-канальное серое изображение\n",
    "                        hand = cv2.cvtColor(hand, cv2.COLOR_BGR2GRAY)\n",
    "                        hand = cv2.GaussianBlur(hand, (blurValue, blurValue), 0)\n",
    "                        # Превращаем в 1-канальное черно-белое изображение\n",
    "                        (thresh, hand) = cv2.threshold(hand, 60, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)\n",
    "                        cv2.imshow('bwhand', hand)\n",
    "\n",
    "                        # Далее мы подготавливаем наш кадр для считывания нс\n",
    "                        # Для этого перегоним его в формат pil_image\n",
    "                        hand = Image.fromarray(hand)\n",
    "                        #face = face.resize((48,48))\n",
    "                        hand = np.asarray(hand).astype('float')\n",
    "                        hand = torch.as_tensor(hand)\n",
    "\n",
    "\n",
    "                        # Превращаем numpy-картинку вырезанного лица в pytorch-тензор\n",
    "                        torch_hand = hand.unsqueeze(0).to(self.device).float()\n",
    "                        # Загужаем наш тензор лица в нейронную сеть и получаем предсказание\n",
    "                        emotion = self.emodel(torch_hand[None, ...])\n",
    "                        print(emotion[0])\n",
    "                        # Интерпретируем предсказание как строку нашей эмоции\n",
    "                        emotion[0][3] = emotion[0][3]/1000\n",
    "                        emotion = self.digit_to_classname(emotion[0].argmax().item())\n",
    "                        hand_cv = cv2.rectangle(frame, (x_min, y_min), (x_max, y_max), (0, 255, 0), 2)\n",
    "                        cv2.putText(frame, emotion,\n",
    "                             (x_max, y_max), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 255), 2, cv2.LINE_AA)\n",
    "\n",
    "    \n",
    "\n",
    "                        \n",
    "                except Exception as e:\n",
    "                    print('Something wrong im main cycle!')\n",
    "                    print(f'error : {e}')\n",
    "\n",
    "                # Показываем кадр в окне, и назвываем его(окно) - 'Face Detection'\n",
    "                cv2.imshow('Hands Detection', frame)\n",
    "\n",
    "\n",
    "                # Функция, которая проверяет нажатие на клавишу 'q'\n",
    "                # Если нажатие произошло - выход из цикла. Конец работы приложения\n",
    "                if cv2.waitKey(1) & 0xFF == ord('q'):\n",
    "                    break\n",
    "\n",
    "            # Очищаем все объекты opencv, что мы создали\n",
    "        self.cap.release()\n",
    "        cv2.destroyAllWindows()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3398, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\azhur\\AppData\\Local\\Temp\\ipykernel_836\\3130851973.py\", line 3, in <cell line: 3>\n",
      "    model = ResNet(1,6).to(device)\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 989, in to\n",
      "    return self._apply(convert)\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 641, in _apply\n",
      "    module._apply(fn)\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 641, in _apply\n",
      "    module._apply(fn)\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 664, in _apply\n",
      "    param_applied = fn(param)\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 987, in convert\n",
      "    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\torch\\cuda\\__init__.py\", line 221, in _lazy_init\n",
      "    raise AssertionError(\"Torch not compiled with CUDA enabled\")\n",
      "AssertionError: Torch not compiled with CUDA enabled\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1993, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1118, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1012, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 865, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 799, in format_exception_as_a_whole\n",
      "    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 845, in get_records\n",
      "    style = stack_data.style_with_executing_node(style, \"bg:ansiyellow\")\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n",
      "    class NewStyle(style):\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pygments\\style.py\", line 91, in __new__\n",
      "    ndef[4] = colorformat(styledef[3:])\n",
      "  File \"c:\\Users\\azhur\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pygments\\style.py\", line 58, in colorformat\n",
      "    assert False, \"wrong color format %r\" % text\n",
      "AssertionError: wrong color format 'ansiyellow'\n"
     ]
    }
   ],
   "source": [
    "mtcnn = MTCNN()\n",
    "device = torch.device(\"cuda\")\n",
    "model = ResNet(1,6).to(device)\n",
    "model.load_state_dict(torch.load('./models/gesture_detection_model_state_20_epochs.pth'))\n",
    "\n",
    "# ourResNet = FERModel(1, 7).to(device)\n",
    "# ourResNet.load_state_dict(torch.load('./models/model2_50_epochs.pth'))\n",
    "\n",
    "\n",
    "model.eval()\n",
    "# Создаем объект нашего класса приложения\n",
    "fcd = FaceDetector(mtcnn, mp, model)\n",
    "# Запускаем\n",
    "fcd.run()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.2"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "e0374bbc5b6e8830e1c7992d2b29930f5be5fce85401b20117ea791a8a6544f0"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
